#!/usr/bin/env bash

cp ../server.py ./
rm file0
./server.py 7735 file0 .5
diff ../c/file0 file0 > /dev/null
if [ $? -gt 0 ]
then
  echo Failure: file not transfered
else
  echo Succcess: File transfered
fi
